name = "Test2-Formatter-Cute"
badges = ["github-actions/test.yml", "metacpan"]

module_maker="ModuleBuildTiny"
static_install = "auto"
markdown_maker = "Pod::Markdown::Github"

[release]
branch='main'
